"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, CheckCircle2, CircleAlert, ExternalLink, Layers3, ShieldAlert, TrendingUp } from "lucide-react";
import Link from "next/link";
import { StatusChip } from "@/components/ui/status-chip";
import { api } from "@/lib/api/client";
import { formatPercent } from "@/lib/format";
import type { HomeDashboard as HomeData, Tone } from "@/lib/types/api";

const number = (value: number | null | undefined, digits = 0) => value == null ? "–" : value.toLocaleString("de-DE", { maximumFractionDigits: digits, minimumFractionDigits: digits });
const date = (value?: string | null) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("de-DE", { weekday: "long", day: "2-digit", month: "long", year: "numeric" }) : "–";

export function HomeDashboard() {
  const query = useQuery({ queryKey: ["home-dashboard"], queryFn: api.home, staleTime: 60_000, refetchInterval: 60_000 });
  if (query.isLoading) return <HomeLoading />;
  if (query.error) return <div className="dashboard-section" role="alert">Die Startseite konnte gerade nicht geladen werden. Bitte später erneut versuchen.</div>;
  const data = query.data;
  if (!data) return null;
  const market = data.market.overview;
  const attentionCount = data.priorities.length;
  const qualityTone: Tone = data.data_quality?.decision_status === "blocked" ? "bad" : data.data_quality?.decision_status === "limited" ? "warning" : "good";
  return <div className="space-y-4">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-sm font-semibold text-[#0f766e]">Guten Morgen</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-[#172033]">Dein Börsen-Cockpit</h1><p className="mt-1 text-sm text-[#687386]">{date(data.as_of)} · Datenstand: {data.as_of || "noch nicht verfügbar"}</p></div>
      <Link href="/settings#data-quality" className="inline-flex items-center gap-2 self-start rounded-full border border-[#e3e8ef] bg-white px-3 py-1.5 text-xs font-semibold text-[#687386] hover:text-[#0f766e]"><span className={`size-2 rounded-full ${qualityTone === "good" ? "bg-[#138a57]" : qualityTone === "bad" ? "bg-[#c2413b]" : "bg-[#b7791f]"}`} />{data.data_quality?.summary || "Datenqualität prüfen"}<ExternalLink size={13} /></Link>
    </header>

    <div className="grid grid-cols-2 gap-2.5 xl:grid-cols-4">
      <MetricCard label="Markt" value={market?.phase_label || "Nicht verfügbar"} detail={market ? `${market.warning_count} Warnzeichen` : "Marktdaten fehlen"} tone={marketTone(market?.phase)} />
      <MetricCard label="Chancen" value={data.opportunities.length ? String(data.opportunities.length) : "–"} detail={data.opportunities.length ? "Top-Kandidaten" : "Tagesauswahl fehlt"} tone={data.opportunities.length ? "good" : "neutral"} />
      <MetricCard label="Depot" value={`${data.portfolio.positions_count} Positionen`} detail="offene Positionen" tone={data.portfolio.positions_count ? "good" : "neutral"} />
      <MetricCard label="Prüfen" value={String(attentionCount)} detail="Punkte mit Aufmerksamkeit" tone={attentionCount ? "warning" : "good"} />
    </div>

    <div className="grid items-start gap-4 xl:grid-cols-[1.1fr_0.9fr]">
      <Panel icon={CircleAlert} title="Heute wichtig" detail="Die wichtigsten Punkte für deinen heutigen Börsen-Workflow."><PriorityList data={data} /></Panel>
      <Panel icon={TrendingUp} title="Markt heute" detail={market?.message || "Strukturierte Marktinformationen aus dem letzten Snapshot."}><MarketToday data={data} /></Panel>
    </div>

    <Panel icon={TrendingUp} title="Chancen des Tages" detail="Starke Aktien mit hoher Qualität und aktueller Dynamik."><Opportunities data={data} /></Panel>
    <div className="grid items-start gap-4 xl:grid-cols-2"><Panel icon={ArrowUpRight} title="Seit dem letzten Handelstag" detail="Gespeicherte Veränderungen und neue Dynamik."><Changes data={data} /></Panel><Panel icon={ShieldAlert} title="Dein Depot" detail="Portfolio kompakt und ohne unnötige Detailtiefe."><Portfolio data={data} /></Panel></div>
    <div className="grid items-start gap-4 xl:grid-cols-2"><Panel icon={Layers3} title="Stärkste Industry Groups" detail="Nur vorhandene Industry-Group-RS-Snapshots."><Groups data={data} /></Panel><Panel icon={CheckCircle2} title="Meine Watchlist" detail="Gespeicherte Watchlist mit dem letzten Assessment-Snapshot."><Watchlist data={data} /></Panel></div>
    {data.errors.length ? <p className="text-xs text-[#8a94a6]">Einzelne Bereiche sind derzeit nicht verfügbar: {data.errors.join(", ")}. Details bleiben auf den jeweiligen Unterseiten verfügbar.</p> : null}
  </div>;
}

function Panel({ icon: Icon, title, detail, children }: { icon: typeof CircleAlert; title: string; detail: string; children: React.ReactNode }) { return <section className="dashboard-section"><div className="mb-3 flex items-start gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-[9px] bg-[#e8f4f2] text-[#0f766e]"><Icon size={16} /></span><div><h2 className="text-sm font-semibold text-[#172033]">{title}</h2><p className="mt-0.5 text-xs leading-5 text-[#687386]">{detail}</p></div></div>{children}</section>; }
function MetricCard({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: Tone }) { const color = tone === "good" ? "#138a57" : tone === "bad" ? "#c2413b" : tone === "warning" ? "#b7791f" : "#2563eb"; return <div className="rounded-[12px] border border-[#e3e8ef] border-t-2 bg-white px-3.5 py-3 shadow-[0_4px_14px_rgba(15,23,42,0.04)]" style={{ borderTopColor: color }}><div className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#687386]">{label}</div><div className="mt-1 truncate text-lg font-semibold text-[#172033]">{value}</div><div className="mt-1 line-clamp-2 text-xs leading-5 text-[#687386]">{detail}</div></div>; }
function PriorityList({ data }: { data: HomeData }) { return data.priorities.length ? <div className="divide-y divide-[#e8edf2]">{data.priorities.map((item) => <Link key={`${item.ticker}-${item.label}`} href={item.href} className="grid gap-2 py-2.5 first:pt-0 last:pb-0 sm:grid-cols-[82px_130px_1fr_auto] sm:items-center"><b>{item.ticker}</b><StatusChip tone={item.tone}>{item.label}</StatusChip><span className="truncate text-sm text-[#687386]">{item.detail}</span><ArrowUpRight className="hidden size-4 text-[#8b95a5] sm:block" /></Link>)}</div> : <Empty text="Heute gibt es keine dringenden Punkte." />; }
function MarketToday({ data }: { data: HomeData }) { const m = data.market.overview; const n = data.market.nasdaq; const b = data.market.breadth; const v = data.market.volatility; const kpi = (source: typeof m, labels: string[]) => source?.kpis.find((item) => labels.some((label) => item.label.toLowerCase().includes(label)))?.value || "–"; return <div className="grid grid-cols-2 gap-2 text-sm"><Data label="Marktphase" value={m?.phase_label || "–"} /><Data label="S&P 500" value={kpi(m, ["s&p", "sp500"])} /><Data label="Nasdaq" value={kpi(n, ["nasdaq", "ixic"])} /><Data label="Marktbreite" value={b?.pct_above_50sma == null ? "–" : `${number(b.pct_above_50sma, 1)} % über 50 SMA`} /><Data label="VIX" value={v?.vix_close == null ? "–" : number(v.vix_close, 1)} /><Data label="Warnzeichen" value={m ? String(m.warning_count) : "–"} /></div>; }
function Opportunities({ data }: { data: HomeData }) { return data.opportunities.length ? <div className="grid gap-2 md:grid-cols-3">{data.opportunities.map((row) => <Link key={row.ticker} href={`/stocks/${row.ticker}`} className="rounded-[10px] border border-[#e3e8ef] bg-[#fbfcfe] p-3 hover:border-[#b7d9d3]"><div className="flex justify-between gap-2"><div><div className="text-xs font-semibold text-[#0f766e]">#{row.rank}</div><div className="mt-1 font-semibold">{row.ticker}</div><div className="text-xs text-[#687386]">{row.name}</div></div><div className="text-right"><div className="text-xl font-semibold text-[#0f766e]">{number(row.daily_opportunity_score, 1)}</div><div className="text-[11px] text-[#687386]">Daily Score</div></div></div><div className="mt-3 text-xs text-[#687386]">Qualität {number(row.quality_score)} · RS {number(row.rs_rating)}</div><div className="mt-2 line-clamp-2 text-xs text-[#475569]">{row.reasons.slice(0, 2).join(" · ") || "Keine Begründung gespeichert"}</div></Link>)}</div> : <Empty text="Die Tagesauswahl wird nach dem nächsten Aktienranking verfügbar." />; }
function Changes({ data }: { data: HomeData }) { return data.changes.length ? <div className="space-y-1.5">{data.changes.map((row, index) => <Link key={`${row.ticker}-${index}`} href={row.href} className="flex gap-3 rounded-[9px] bg-[#f7f9fb] px-3 py-2"><span className="font-semibold">{row.ticker}</span><span className="text-sm text-[#687386]">{row.detail}</span></Link>)}</div> : <Empty text="Keine neuen Veränderungen im gespeicherten Vergleich." />; }
function Portfolio({ data }: { data: HomeData }) { const p = data.portfolio; const attention = data.sell_rows.filter((row) => row.status !== "Halten").slice(0, 4); return <><div className="grid grid-cols-2 gap-2"><Data label="Positionen" value={String(p.positions_count)} /><Data label="Stop-Abdeckung" value={p.stop_coverage_total ? `${number((p.stop_coverage_count || 0) / p.stop_coverage_total * 100)} %` : "–"} /></div><div className="mt-3 space-y-1.5">{(attention.length ? attention : p.positions.slice(0, 3)).map((row) => <Link key={row.ticker} href={`/sell-monitor/${row.ticker}`} className="flex items-center justify-between rounded-[9px] bg-[#f7f9fb] px-3 py-2"><span><b>{row.ticker}</b>{"pnl_pct" in row ? <span className="ml-2 text-xs text-[#687386]">{formatPercent(row.pnl_pct)}</span> : null}</span>{"status" in row ? <StatusChip tone={row.status === "Verkaufen" ? "bad" : "warning"}>{row.status}</StatusChip> : null}</Link>)}</div><Link className="mt-3 inline-flex text-sm font-semibold text-[#0f766e]" href="/portfolio">Portfolio öffnen <ArrowUpRight size={14} /></Link></>; }
function Groups({ data }: { data: HomeData }) { return data.industry_groups.length ? <div className="space-y-1.5">{data.industry_groups.map((row) => <Link key={row.code} href={`/industry-groups/${row.code}`} className="flex items-center justify-between gap-2 rounded-[9px] bg-[#f7f9fb] px-3 py-2"><span><b>#{row.rank || "–"} {row.name}</b><span className="ml-2 text-xs text-[#687386]">RS {number(row.rs_score, 0)}</span></span><span className="text-xs font-semibold text-[#138a57]">{row.rank_change_20d == null ? "" : `${row.rank_change_20d > 0 ? "↑" : "↓"} ${Math.abs(row.rank_change_20d)}`}</span></Link>)}</div> : <Empty text="Noch keine Industry-Group-Rangliste verfügbar." />; }
function Watchlist({ data }: { data: HomeData }) { return data.watchlist.length ? <div className="space-y-1.5">{data.watchlist.map((row) => <Link key={row.ticker} href={`/stocks/${row.ticker}`} className="flex items-center justify-between rounded-[9px] bg-[#f7f9fb] px-3 py-2"><span><b>{row.ticker}</b><span className="ml-2 text-xs text-[#687386]">Score {row.overall_score}</span></span><StatusChip tone={row.warnings_count ? "warning" : "good"}>{row.top_warning || "Snapshot vorhanden"}</StatusChip></Link>)}</div> : <Empty text="Noch keine Watchlist oder keine gespeicherten Assessment-Snapshots." />; }
function Data({ label, value }: { label: string; value: string }) { return <div className="rounded-[9px] bg-[#f7f9fb] px-3 py-2"><div className="text-xs text-[#687386]">{label}</div><div className="mt-0.5 font-semibold">{value}</div></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-[9px] border border-dashed border-[#d8e1ea] bg-[#fafcfd] px-3 py-3 text-sm text-[#687386]">{text}</div>; }
function HomeLoading() { return <div className="space-y-4" aria-busy="true"><div className="h-20 animate-pulse rounded-[12px] bg-[#e9eef3]" /><div className="grid grid-cols-2 gap-2.5 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div className="h-24 animate-pulse rounded-[12px] bg-[#e9eef3]" key={item} />)}</div><div className="grid gap-4 xl:grid-cols-2">{[1, 2].map((item) => <div className="h-52 animate-pulse rounded-[14px] bg-[#e9eef3]" key={item} />)}</div></div>; }
function marketTone(phase?: string): Tone { return phase === "aufwaertstrend" || phase === "gruen" ? "good" : phase === "rot" ? "bad" : phase ? "warning" : "neutral"; }
