from __future__ import annotations

import re


def _normalize(value: str) -> str:
    text = str(value or "").strip().lower()
    text = text.replace("&", " and ")
    text = re.sub(r"[-_/]+", " ", text)
    text = re.sub(r"\btechnologies\b", "technology", text)
    text = re.sub(r"\bsemiconductors\b", "semiconductor", text)
    text = re.sub(r"\brestaurants\b", "restaurant", text)
    text = re.sub(r"\bbanks\b", "bank", text)
    text = re.sub(r"\bdevices\b", "device", text)
    text = re.sub(r"\bservices\b", "service", text)
    return re.sub(r"\s+", " ", text).strip()


# Stable provider-industry -> canonical v4 group rules.
# tuple: code, group name, sector, family, confidence
_RAW_PROVIDER_RULES: dict[str, tuple[str, str, str, str, float]] = {
    "Engineering & Construction": ("ENGCONST", "Engineering & Construction", "Industrials", "Construction & Engineering", 0.92),
    "Electrical Equipment & Parts": ("ELECEQP", "Electrical Equipment & Parts", "Industrials", "Electrical Equipment", 0.92),
    "Medical Care Facilities": ("MEDCARE", "Medical Care Facilities", "Health Care", "Health Care Services", 0.92),
    "Real Estate Services": ("REALESVC", "Real Estate Services", "Real Estate", "Real Estate", 0.92),
    "Building Products & Equipment": ("BLDGPROD", "Building Products & Equipment", "Industrials", "Construction & Building Products", 0.92),
    "REIT - Mortgage": ("REITMORT", "Real Estate – Mortgage REIT", "Real Estate", "REIT", 0.93),
    "Health Information Services": ("HEALTHIT", "Health Information Services", "Health Care", "Health Care Technology", 0.92),
    "Advertising Agencies": ("ADVERT", "Advertising Agencies", "Communication Services", "Media & Advertising", 0.91),
    "Apparel Retail": ("RETAILAPP", "Retail – Apparel", "Consumer Discretionary", "Retail", 0.92),
    "Communication Equipment": ("COMMEQP", "Communication Equipment", "Technology", "Communications Equipment", 0.92),
    "Utilities - Regulated Electric": ("UTILREGEL", "Utilities – Regulated Electric", "Utilities", "Utilities", 0.94),
    "Education & Training Services": ("EDUCATION", "Education & Training Services", "Consumer Staples", "Consumer Services", 0.90),
    "Leisure": ("LEISURE", "Leisure – General", "Consumer Discretionary", "Leisure", 0.86),
    "Oil & Gas Midstream": ("OILMID", "Energy – Midstream", "Energy", "Oil & Gas", 0.94),
    "Scientific & Technical Instruments": ("SCIINST", "Scientific & Technical Instruments", "Technology", "Instruments & Electronics", 0.92),
    "Integrated Freight & Logistics": ("FREIGHT", "Transportation – Freight & Logistics", "Industrials", "Transportation", 0.93),
    "Furnishings, Fixtures & Appliances": ("HOMEFURN", "Consumer – Furnishings & Appliances", "Consumer Discretionary", "Household Durables", 0.91),
    "Apparel Manufacturing": ("APPARELMFG", "Apparel – Manufacturing", "Consumer Discretionary", "Apparel", 0.91),
    "Auto & Truck Dealerships": ("AUTODEAL", "Auto – Dealerships", "Consumer Discretionary", "Automotive Retail", 0.92),
    "Consulting Services": ("CONSULT", "Commercial – Consulting Services", "Industrials", "Professional Services", 0.91),
    "Conglomerates": ("CONGLOM", "Industrials – Conglomerates", "Industrials", "Diversified Industrials", 0.90),
    "Packaging & Containers": ("PACKAGING", "Packaging & Containers", "Consumer Discretionary", "Packaging", 0.91),
    "Industrial Distribution": ("INDDIST", "Industrial Distribution", "Industrials", "Distribution", 0.92),
    "Insurance Brokers": ("INSBROKER", "Insurance – Brokers", "Financials", "Insurance", 0.93),
    "Waste Management": ("WASTE", "Commercial – Waste Management", "Industrials", "Environmental Services", 0.93),
    "Farm Products": ("FARMPROD", "Food – Farm Products", "Consumer Staples", "Food & Agriculture", 0.91),
    "Rental & Leasing Services": ("RENTLEASE", "Commercial – Rental & Leasing", "Industrials", "Business Services", 0.91),
    "Staffing & Employment Services": ("STAFFING", "Commercial – Staffing & Employment", "Industrials", "Business Services", 0.91),
    "Other Precious Metals & Mining": ("MINPREC", "Mining – Other Precious Metals", "Materials", "Metals & Mining", 0.92),
    "REIT - Office": ("REITOFF", "Real Estate – Office REIT", "Real Estate", "REIT", 0.93),
    "REIT - Specialty": ("REITSPEC", "Real Estate – Specialty REIT", "Real Estate", "REIT", 0.92),
    "Broadcasting": ("BROADCAST", "Media – Broadcasting", "Communication Services", "Media & Entertainment", 0.92),
    "REIT - Healthcare Facilities": ("REITHEALTH", "Real Estate – Healthcare REIT", "Real Estate", "REIT", 0.93),
    "Recreational Vehicles": ("RECVHC", "Auto – Recreational Vehicles", "Consumer Discretionary", "Automotive & Leisure", 0.91),
    "Insurance - Specialty": ("INSSPEC", "Insurance – Specialty", "Financials", "Insurance", 0.93),
    "Metal Fabrication": ("METALFAB", "Industrials – Metal Fabrication", "Industrials", "Metals & Machinery", 0.91),
    "Pollution & Treatment Controls": ("POLLCTRL", "Commercial – Pollution & Treatment Controls", "Industrials", "Environmental Services", 0.91),
    "REIT - Diversified": ("REITDIV", "Real Estate – Diversified REIT", "Real Estate", "REIT", 0.92),
    "Security & Protection Services": ("SECURITY", "Commercial – Security & Protection", "Industrials", "Business Services", 0.91),
    "Consumer Electronics": ("CONSELEC", "Electronics – Consumer", "Technology", "Hardware", 0.92),
    "Footwear & Accessories": ("FOOTWEAR", "Apparel – Footwear & Accessories", "Consumer Discretionary", "Apparel", 0.92),
    "Solar": ("SOLAR", "Energy – Solar", "Technology", "Renewable Energy", 0.93),
    "Uranium": ("URANIUM", "Energy – Uranium", "Energy", "Energy & Mining", 0.93),
    "Personal Services": ("PERSERV", "Consumer – Personal Services", "Consumer Discretionary", "Consumer Services", 0.90),
    "Agricultural Inputs": ("AGRIINPUT", "Materials – Agricultural Inputs", "Materials", "Agriculture", 0.92),
    "Financial Data & Stock Exchanges": ("FINDATA", "Finance – Data & Stock Exchanges", "Financials", "Financial Services", 0.94),
    "Healthcare Plans": ("HEALTHPLAN", "Medical – Healthcare Plans", "Health Care", "Health Care Services", 0.93),
    "Mortgage Finance": ("MORTFIN", "Finance – Mortgage Finance", "Financials", "Financial Services", 0.92),
    "Tools & Accessories": ("TOOLS", "Machinery – Tools & Accessories", "Industrials", "Machinery & Tools", 0.91),
    "Travel Services": ("TRAVEL", "Leisure – Travel Services", "Consumer Discretionary", "Travel & Leisure", 0.92),
    "Utilities - Regulated Gas": ("UTILREGGAS", "Utilities – Regulated Gas", "Utilities", "Utilities", 0.94),
    "Utilities - Regulated Water": ("UTILWATER", "Utilities – Regulated Water", "Utilities", "Utilities", 0.94),
    "Tobacco": ("TOBACCO", "Consumer – Tobacco", "Consumer Staples", "Consumer Products", 0.94),
    "Food Distribution": ("FOODDIST", "Food – Distribution", "Consumer Staples", "Food & Beverage", 0.92),
    "Luxury Goods": ("LUXURY", "Consumer – Luxury Goods", "Consumer Discretionary", "Consumer Products", 0.91),
    "Publishing": ("PUBLISH", "Media – Publishing", "Communication Services", "Media & Entertainment", 0.91),
    "Real Estate - Development": ("REDEV", "Real Estate – Development", "Real Estate", "Real Estate", 0.92),
    "Discount Stores": ("RETAILDISC", "Retail – Discount Stores", "Consumer Staples", "Retail", 0.93),
    "Electronics & Computer Distribution": ("TECHDIST", "Computer – Distribution", "Technology", "Technology Distribution", 0.91),
    "Insurance - Diversified": ("INSDIV", "Insurance – Diversified", "Financials", "Insurance", 0.92),
    "Airports & Air Services": ("AIRPORT", "Transportation – Airports & Air Services", "Industrials", "Transportation", 0.92),
    "Medical Distribution": ("MEDDIST", "Medical – Distribution", "Health Care", "Health Care Distribution", 0.92),
    "Home Improvement Retail": ("RETAILHOME", "Retail – Home Improvement", "Consumer Discretionary", "Retail", 0.93),
    "Silver": ("SILVER", "Mining – Silver", "Materials", "Metals & Mining", 0.94),
    "Business Equipment & Supplies": ("BUSINEQP", "Commercial – Business Equipment & Supplies", "Industrials", "Business Services", 0.90),
    "Confectioners": ("CONFECT", "Food – Confectioners", "Consumer Staples", "Food & Beverage", 0.92),
    "Lumber & Wood Production": ("LUMBER", "Materials – Lumber & Wood", "Materials", "Materials", 0.92),
    "Utilities - Diversified": ("UTILDIV", "Utilities – Diversified", "Utilities", "Utilities", 0.92),
    "Aluminum": ("ALUMINUM", "Metals – Aluminum", "Materials", "Metals & Mining", 0.94),
    "Coking Coal": ("COKECOAL", "Mining – Coking Coal", "Materials", "Coal", 0.94),
    "Department Stores": ("DEPTSTORE", "Retail – Department Stores", "Consumer Discretionary", "Retail", 0.92),
    "Paper & Paper Products": ("PAPER", "Materials – Paper & Paper Products", "Materials", "Materials", 0.92),
    "Textile Manufacturing": ("TEXTILE", "Apparel – Textile Manufacturing", "Consumer Discretionary", "Textiles & Apparel", 0.91),
    "Thermal Coal": ("THERMCOAL", "Energy – Thermal Coal", "Energy", "Coal", 0.94),
    "Utilities - Independent Power Producers": ("UTILIPP", "Utilities – Independent Power Producers", "Utilities", "Utilities", 0.92),
    "Financial Conglomerates": ("FINCONG", "Finance – Conglomerates", "Financials", "Financial Services", 0.90),
    "Insurance - Reinsurance": ("INSRE", "Insurance – Reinsurance", "Financials", "Insurance", 0.94),
    "Oil & Gas Drilling": ("OILDRILL", "Energy – Oil & Gas Drilling", "Energy", "Oil & Gas", 0.94),

    # Durable splits supported directly by the provider taxonomy.
    "Drug Manufacturers - Specialty & Generic": ("PHARMA_SPEC", "Medical – Pharmaceuticals Specialty & Generic", "Health Care", "Medical", 0.95),
    "Drug Manufacturers - General": ("PHARMA_GEN", "Medical – Pharmaceuticals General", "Health Care", "Medical", 0.95),
    "Pharmaceutical Retailers": ("PHARMA_RETAIL", "Medical – Pharmaceutical Retail", "Health Care", "Medical", 0.90),
    "Medical Instruments & Supplies": ("MEDINSTR", "Medical – Instruments & Supplies", "Health Care", "Medical", 0.95),
    "Medical Devices": ("MEDDEV", "Medical – Devices", "Health Care", "Medical", 0.95),
    "Specialty Industrial Machinery": ("MACHSPEC", "Machinery – Specialty Industrial", "Industrials", "Machinery", 0.94),
    "Farm & Heavy Construction Machinery": ("MACHHEAVY", "Machinery – Farm & Heavy Construction", "Industrials", "Machinery", 0.94),
    "REIT - Hotel & Motel": ("REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.94),
    "Resorts & Casinos": ("CASINO", "Leisure – Casinos & Resorts", "Consumer Discretionary", "Leisure", 0.94),
    "Electronic Gaming & Multimedia": ("GAMEDEV", "Leisure – Electronic Gaming", "Consumer Discretionary", "Leisure", 0.94),
    "Gambling": ("CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.94),
    "Beverages - Non-Alcoholic": ("BEVNONALC", "Food – Non-Alcoholic Beverages", "Consumer Staples", "Food & Beverage", 0.94),
    "Beverages - Wineries & Distilleries": ("BEVALC", "Food – Alcoholic Beverages", "Consumer Staples", "Food & Beverage", 0.94),
    "Beverages - Brewers": ("BEVALC", "Food – Alcoholic Beverages", "Consumer Staples", "Food & Beverage", 0.94),
}

V4_CANONICAL_PROVIDER_INDUSTRIES = {
    _normalize(industry): definition for industry, definition in _RAW_PROVIDER_RULES.items()
}


# Current-universe exceptions where the provider label is too broad for a clean
# peer group. The company-name fragment prevents accidental ticker reuse.
V4_REVIEWED_COMPANY_RULES: dict[str, tuple[str, str, str, str, str, float]] = {
    "V": ("visa", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.99),
    "MA": ("mastercard", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.99),
    "PYPL": ("paypal", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.99),
    "WU": ("western union", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.98),
    "GDOT": ("green dot", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.96),
    "FISV": ("fiserv", "PAYPROC", "Finance – Payments & Transaction Processing", "Financials", "Financial Services", 0.99),

    "BBDC": ("barings bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "BCSF": ("bain capital specialty finance", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "CCAP": ("crescent capital bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "CION": ("cion investment", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "CSWC": ("capital southwest", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "FSK": ("fs kkr capital", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "GAIN": ("gladstone investment", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "GSBD": ("goldman sachs bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "HRZN": ("horizon technology finance", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "HTGC": ("hercules capital", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "ICMB": ("investcorp credit management bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "KBDC": ("kayne anderson bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "LIEN": ("chicago atlantic bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "MAIN": ("main street capital", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "NCDL": ("nuveen churchill direct lending", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "NMFC": ("new mountain finance", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "OBDC": ("blue owl capital corporation", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "OTF": ("blue owl technology finance", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "PFLT": ("pennantpark floating rate", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "PFX": ("phenixfin", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.97),
    "PNNT": ("pennantpark investment", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "PSBD": ("palmer square capital bdc", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "RWAY": ("runway growth finance", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "SAR": ("saratoga investment", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.97),
    "SCM": ("stellus capital investment", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "TPVG": ("triplepoint venture growth", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "TRIN": ("trinity capital", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.97),
    "TSLX": ("sixth street specialty lending", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),

    # Current-universe corrections found during the v4 audit.
    "AFCG": ("advanced flower capital", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.99),
    "EQS": ("equus total return", "BDC", "Finance – Business Development Companies", "Financials", "Financial Services", 0.98),
    "MLCI": ("mount logan capital", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "RPC": ("ridgepost capital", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "BUR": ("burford capital", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "MORN": ("morningstar", "FINDATA", "Finance – Data & Stock Exchanges", "Financials", "Financial Services", 0.99),
    "VALU": ("value line", "FINDATA", "Finance – Data & Stock Exchanges", "Financials", "Financial Services", 0.98),
    "PJT": ("pjt partners", "CAPMARK", "Finance – Capital Markets", "Financials", "Financial Services", 0.99),
    "CRBG": ("corebridge financial", "INSLIFE", "Insurance – Life", "Financials", "Insurance", 0.99),
    "EQH": ("equitable holdings", "INSDIV", "Insurance – Diversified", "Financials", "Insurance", 0.97),
    "PFG": ("principal financial group", "INSDIV", "Insurance – Diversified", "Financials", "Insurance", 0.96),
    "KWY": ("kingsway corporation", "BUSSERV", "Commercial – Business Services", "Industrials", "Business Services", 0.96),
    "RILY": ("brc group holdings", "FINCONG", "Finance – Conglomerates", "Financials", "Financial Services", 0.96),
    "TGE": ("generation essentials group", "ENTERTAIN", "Media – Entertainment", "Communication Services", "Media & Entertainment", 0.92),
    "ALP": ("alpha compute", "ITSVC", "Computer – IT Services", "Technology", "IT Services", 0.96),

    # Digital-asset treasury / on-chain holding companies are driven by token
    # exposure and treasury economics rather than traditional asset-management fees.
    "ASST": ("strive", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.98),
    "AVAT": ("avalanche treasury", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.99),
    "CYPH": ("cypherpunk", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.97),
    "DFDV": ("defi development", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.99),
    "FGNX": ("fg nexus", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.99),
    "HSDT": ("solana company", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.99),
    "SDEV": ("stablecoin development", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.99),
    "TWAV": ("taoweave", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.98),
    "ZSTK": ("zerostack", "DATTREAS", "Finance – Digital Asset Treasury", "Financials", "Digital Assets", 0.94),

    "ALTI": ("alti global", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "CWD": ("calibercos", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "DBRG": ("digitalbridge", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "HLNE": ("hamilton lane", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "APO": ("apollo global management", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "ARES": ("ares management", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "BAM": ("brookfield asset management", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "BN": ("brookfield corporation", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.97),
    "BX": ("blackstone", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "CG": ("carlyle group", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "GCMG": ("gcm grosvenor", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "KKR": ("kkr", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "OWL": ("blue owl capital inc", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),
    "PAX": ("patria investments", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.97),
    "STEP": ("stepstone group", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.98),
    "TPG": ("tpg inc", "ALTMGR", "Finance – Alternative Asset Managers", "Financials", "Financial Services", 0.99),

    "HST": ("host hotels", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.98),
    "INN": ("summit hotel properties", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.98),
    "PEB": ("pebblebrook hotel trust", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.99),
    "PK": ("park hotels", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.99),
    "SHO": ("sunstone hotel investors", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.99),
    "XHR": ("xenia hotels", "REITHOTEL", "Real Estate – Hotel REIT", "Real Estate", "REIT", 0.98),
    "FLL": ("full house resorts", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.98),
    "MCRI": ("monarch casino", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "MGM": ("mgm resorts", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "RRR": ("red rock resorts", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "WYNN": ("wynn resorts", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "BYD": ("boyd gaming", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "CNTY": ("century casinos", "CASINO", "Leisure – Casinos & Gambling", "Consumer Discretionary", "Leisure", 0.99),
    "GLPI": ("gaming and leisure properties", "REITSPEC", "Real Estate – Specialty REIT", "Real Estate", "REIT", 0.98),

    "ASIX": ("advansix", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.92),
    "BAK": ("braskem", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.94),
    "CE": ("celanese", "CHEMSPEC", "Chemicals – Specialty", "Materials", "Chemicals", 0.92),
    "DOW": ("dow inc", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.95),
    "GPRE": ("green plains", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.88),
    "GURE": ("gulf resources", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.91),
    "HUN": ("huntsman", "CHEMSPEC", "Chemicals – Specialty", "Materials", "Chemicals", 0.91),
    "LXU": ("lsb industries", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.91),
    "MEOH": ("methanex", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.95),
    "NPT": ("texxon holding", "INDDIST", "Industrial Distribution", "Industrials", "Distribution", 0.82),
    "OLN": ("olin corporation", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.94),
    "REX": ("rex american resources", "CHEMCOMM", "Chemicals – Commodity", "Materials", "Chemicals", 0.90),
    "RYAM": ("rayonier advanced materials", "CHEMSPEC", "Chemicals – Specialty", "Materials", "Chemicals", 0.88),

    "BEEP": ("mobile infrastructure", "REALPARK", "Real Estate – Parking Infrastructure", "Real Estate", "Real Estate", 0.96),
    "JOE": ("joe company", "REDEV", "Real Estate – Development", "Real Estate", "Real Estate", 0.96),
}
