"""Sell-engine constants exposed for API and UI option generation."""

from app.domain.sell.rules import (
    ALLOWED_RECOMMENDATION_LEVELS,
    BEARISH_MARKET_LABEL,
    DEFENSIVE_MODE,
    LM_HUB_PROFILE_DEFAULT,
    LM_HUB_PROFILES,
    LM_HUB_STRATEGIES_ALL,
    LM_HUB_STRATEGIEN,
    LM_HUB_STRATEGIEN_DEFAULT,
    LM_HUB_WARNUNGEN,
    LM_HUB_WARNUNGEN_DEFAULT,
    STRENGTH_DEFENSIVE_MODE,
    STRENGTH_OFFENSIVE_MODE,
)

SELL_DECISION_MARKET_ENVIRONMENTS = {"Bullisch", "Unsicher", "Bärisch"}
SELL_DECISION_INDUSTRY_GROUP_STATUSES = {"Stark", "Neutral", "Schwach"}

__all__ = [
    "ALLOWED_RECOMMENDATION_LEVELS",
    "BEARISH_MARKET_LABEL",
    "DEFENSIVE_MODE",
    "LM_HUB_PROFILE_DEFAULT",
    "LM_HUB_PROFILES",
    "LM_HUB_STRATEGIES_ALL",
    "LM_HUB_STRATEGIEN",
    "LM_HUB_STRATEGIEN_DEFAULT",
    "LM_HUB_WARNUNGEN",
    "LM_HUB_WARNUNGEN_DEFAULT",
    "SELL_DECISION_INDUSTRY_GROUP_STATUSES",
    "SELL_DECISION_MARKET_ENVIRONMENTS",
    "STRENGTH_DEFENSIVE_MODE",
    "STRENGTH_OFFENSIVE_MODE",
]

